spring:
  application:
    name: gateway-server
  profiles:
    active: localhost

  cloud:
    gateway:
      routes:
        - id: ms1
          uri: lb://MS1
          predicates:
            - name: Path
              args:
                pattern: /ms1/**
          filters:
            - name: L1Filter
              args:
                pre: true
                post: true
        - id: ms2
          uri: http://localhost:8082
          predicates:
            - Path=/ms2/**

server:
  port: 8080


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
